### ISSUE TITLE
Makefile refers to missing dependency coveralls

### ISSUE THREAD

**Issue by noahnu** [tophat/commit-watch#10]
At https://github.com/tophat/commit-watch/blob/273c4f52981e0e92f981e58e31629c58d9186b64/Makefile#L9 we use coveralls, however this repo doesn't currently have code coverage setup.

We can either remove coveralls, or configure code coverage. Same with jest-juint

**Comment by mcataford** [comment]
I'll take this on. 🚀

**Comment by noahnu** [comment]
Fixed in master
